In [1]:
print("Second Notebook")

Second Notebook

In [2]:
import pandas as pd
import numpy as np

In [3]:
ml_table = pd.read_csv("C:\\Users\\Anwar Altorkmani\\Desktop\\Task2\\olist_ml_table_new_new_new.csv")

print("Shape:", ml_table.shape)
ml_table.head()

Shape: (99441, 37)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,is_weekend,multi_seller,freight_ratio,freight_per_item,total_weight,total_volume,avg_volume,max_volume,distance_km,is_cross_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,0,0,0.290764,8.72,500.0,1976.0,1976.0,1976.0,18.576110,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,0,0,0.191744,22.76,400.0,4693.0,4693.0,4693.0,851.495069,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,0,0,0.120200,19.22,420.0,9576.0,9576.0,9576.0,514.410666,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,...,1,0,0.604444,27.20,450.0,6000.0,6000.0,6000.0,1822.226336,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,0,0,0.438191,8.72,250.0,11475.0,11475.0,11475.0,29.676625,0

In [4]:
date_columns = [
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

print(ml_table[date_columns].head())

  order_delivered_customer_date order_estimated_delivery_date
0           2017-10-10 21:25:13           2017-10-18 00:00:00
1           2018-08-07 15:27:45           2018-08-13 00:00:00
2           2018-08-17 18:06:29           2018-09-04 00:00:00
3           2017-12-02 00:28:42           2017-12-15 00:00:00
4           2018-02-16 18:17:02           2018-02-26 00:00:00

In [5]:
print(ml_table[date_columns].isna().sum())

order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [6]:
ml_table["order_delivered_customer_date"] = pd.to_datetime(
    ml_table["order_delivered_customer_date"],
    errors="coerce"
)

ml_table["order_estimated_delivery_date"] = pd.to_datetime(
    ml_table["order_estimated_delivery_date"],
    errors="coerce"
)

In [7]:
print(ml_table[
    [
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
].dtypes)

order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [8]:
labeled_table = ml_table[
    ml_table["order_delivered_customer_date"].notna() &
    ml_table["order_estimated_delivery_date"].notna()
].copy()

In [9]:
print("Original rows:", len(ml_table))
print("Labeled rows:", len(labeled_table))
print("Removed rows:", len(ml_table) - len(labeled_table))

Original rows: 99441
Labeled rows: 96476
Removed rows: 2965

In [10]:
labeled_table["is_late"] = (
    labeled_table["order_delivered_customer_date"]
    >
    labeled_table["order_estimated_delivery_date"]
).astype(int)

In [11]:
labeled_table["delivery_delay_days"] = (
    labeled_table["order_delivered_customer_date"]
    -
    labeled_table["order_estimated_delivery_date"]
).dt.total_seconds() / 86400

In [12]:
labeled_table[
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_delay_days",
        "is_late"
    ]
].head(10)

,order_id,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,is_late
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-10 21:25:13,2017-10-18,-7.107488,0
1,53cdb2fc8bc7dce0b6741e2150273451,2018-08-07 15:27:45,2018-08-13,-5.355729,0
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-17 18:06:29,2018-09-04,-17.245498,0
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-12-02 00:28:42,2017-12-15,-12.980069,0
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-16 18:17:02,2018-02-26,-9.238171,0
5,a4591c265e18cb1dcee52889e2d8acc3,2017-07-26 10:57:55,2017-08-01,-5.543113,0
7,6514b8ad8028c9f2cc2374ded245783f,2017-05-26 12:55:51,2017-06-07,-11.461215,0
8,76c6e866289321a7c93b82b54852dc33,2017-02-02 14:08:10,2017-03-06,-31.410995,0
9,e69bfb5eb88e0ed6a785585b27e16dbf,2017-08-16 17:14:30,2017-08-23,-6.281597,0
10,e6ce16cb79ec1d90b1da9085a6118aeb,2017-05-29 11:18:31,2017-06-07,-8.528808,0

In [13]:
labeled_table[
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_delay_days",
        "is_late"
    ]
].sample(10, random_state=42)

,order_id,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,is_late
22500,c58cff333993bb6b7161d7ec1350eef3,2018-04-06 02:32:49,2018-04-18,-11.893877,0
68941,87673b5ccb20de0a91c28cc461105d76,2018-05-23 15:28:28,2018-05-30,-6.355231,0
23988,80b430d0029bb33110ac31d60e87e0b8,2017-12-07 18:43:46,2017-12-27,-19.219606,0
31303,580603672a21252f21fa8a8b4ca85986,2018-04-26 17:44:27,2018-05-08,-11.260799,0
36131,c09f32e7ba9b4a134455b36eeff8fff3,2018-04-13 17:32:07,2018-04-24,-10.269363,0
58330,462240cb1ec4e5db517e73fff57ebfc0,2017-12-14 18:56:14,2017-12-20,-5.210949,0
95960,5bc2a7b8f0817443a86b69461e742cc9,2018-01-12 21:59:18,2018-02-01,-19.083819,0
56131,4ef8f514f95bb0a41f58965ea04e7027,2017-05-26 15:59:47,2017-06-07,-11.333484,0
56750,587904dc1c873ebfb6078160b4819d8e,2017-12-06 19:43:34,2017-12-15,-8.178079,0
92212,29c3b79aace1b72a82b1232bf494e16f,2018-04-28 15:51:50,2018-01-24,94.660995,1

In [14]:
labeled_table[
    labeled_table["is_late"] == 1
][
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_delay_days",
        "is_late"
    ]
].head(5)

,order_id,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,is_late
20,203096f03d82e0dffbc41ebc2e2bcfb7,2017-10-09 22:23:46,2017-09-28,11.933171,1
25,fbf9ac61453ac646ce8ad9783d7d0af6,2018-03-21 22:03:54,2018-03-12,9.919375,1
35,8563039e855156e48fccee4d611a3196,2018-03-20 00:59:25,2018-03-20,0.041262,1
41,6ea2f835b4556291ffdc53fa0b3b95e8,2017-12-28 18:59:23,2017-12-21,7.791238,1
57,66e4624ae69e7dc89bd50222b59f581f,2018-04-03 13:28:46,2018-04-02,1.561644,1

In [15]:
labeled_table[
    labeled_table["is_late"] == 0
][
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
        "delivery_delay_days",
        "is_late"
    ]
].head(5)

,order_id,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,is_late
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-10 21:25:13,2017-10-18,-7.107488,0
1,53cdb2fc8bc7dce0b6741e2150273451,2018-08-07 15:27:45,2018-08-13,-5.355729,0
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-17 18:06:29,2018-09-04,-17.245498,0
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-12-02 00:28:42,2017-12-15,-12.980069,0
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-16 18:17:02,2018-02-26,-9.238171,0

In [16]:
check = (
    (labeled_table["delivery_delay_days"] > 0).astype(int)
    == labeled_table["is_late"]
)

print("All labels correct:", check.all())

All labels correct: True

In [17]:
class_counts = labeled_table["is_late"].value_counts()

print(class_counts)

is_late
0    88649
1     7827
Name: count, dtype: int64

In [18]:
class_percentages = (
    labeled_table["is_late"]
    .value_counts(normalize=True)
    * 100
)

print(class_percentages)

is_late
0    91.887101
1     8.112899
Name: proportion, dtype: float64

In [19]:
distribution = pd.DataFrame({
    "count": class_counts,
    "percentage": class_percentages
})

distribution.index = ["On Time (0)" if i == 0 else "Late (1)" 
                      for i in distribution.index]

distribution

             count  percentage
On Time (0)  88649   91.887101
Late (1)      7827    8.112899

In [21]:
majority_count = labeled_table["is_late"].value_counts().max()
minority_count = labeled_table["is_late"].value_counts().min()

imbalance_ratio = majority_count / minority_count

print("Majority class:", majority_count)
print("Minority class:", minority_count)
print("Imbalance ratio:", round(imbalance_ratio, 2))

Majority class: 88649
Minority class: 7827
Imbalance ratio: 11.33

In [20]:
print("Rows:", len(labeled_table))
print("Unique orders:", labeled_table["order_id"].nunique())
print(
    "Duplicate orders:",
    labeled_table["order_id"].duplicated().sum()
)

Rows: 96476
Unique orders: 96476
Duplicate orders: 0

In [21]:
labeled_table = labeled_table.drop(
    columns=["delivery_delay_days"]
)

In [22]:
print(labeled_table.columns.tolist())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'total_items', 'total_price', 'total_freight_value', 'avg_item_price', 'total_payment_value', 'max_installments', 'payment_count', 'main_payment_type', 'unique_products', 'unique_sellers', 'purchase_year', 'purchase_month', 'purchase_day', 'purchase_weekday', 'purchase_hour', 'is_weekend', 'multi_seller', 'freight_ratio', 'freight_per_item', 'total_weight', 'total_volume', 'avg_volume', 'max_volume', 'distance_km', 'is_cross_state', 'is_late']

In [23]:
print("Final shape:", labeled_table.shape)

print("\nLabel distribution:")
print(labeled_table["is_late"].value_counts())

print("\nMissing labels:")
print(labeled_table["is_late"].isna().sum())

print("\nDuplicate orders:")
print(labeled_table["order_id"].duplicated().sum())

Final shape: (96476, 38)

Label distribution:
is_late
0    88649
1     7827
Name: count, dtype: int64

Missing labels:
0

Duplicate orders:
0

In [24]:
labeled_table.to_csv(
    "olist_labeled_ml_table_new.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!