In [1]:
print("First Notebook")

First Notebook

In [2]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine, text

In [3]:
DB_USER = "postgres"
DB_PASSWORD = "postgres"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "postgres"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

print("Database connection created successfully.")

Database connection created successfully.

In [4]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT 1"))
    print(result.fetchone())

(1,)

In [5]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

tables = pd.read_sql(query, engine)

tables

                     table_name
0                     customers
1                   geolocation
2                   order_items
3                order_payments
4                 order_reviews
5                        orders
6  product_category_translation
7                      products
8                       sellers

In [ ]:
orders = pd.read_sql(
    "SELECT * FROM orders",
    engine
)

customers = pd.read_sql(
    "SELECT * FROM customers",
    engine
)

order_items = pd.read_sql(
    "SELECT * FROM order_items",
    engine
)

order_payments = pd.read_sql(
    "SELECT * FROM order_payments",
    engine
)

products = pd.read_sql(
    "SELECT * FROM products",
    engine
)

sellers = pd.read_sql(
    "SELECT * FROM sellers",
    engine
)

geolocation = pd.read_sql(
    "SELECT * FROM geolocation",
    engine
)

In [8]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [9]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [11]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [12]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [13]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [14]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [ ]:
tables = {
    "orders": orders,
    "customers": customers,
    "order_items": order_items,
    "order_payments": order_payments,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation
}

for name, table in tables.items():
    print(f"{name:20} {table.shape}")

orders               (99441, 8)
customers            (99441, 5)
order_items          (112650, 7)
order_payments       (103886, 5)
products             (32951, 9)
sellers              (3095, 4)
geolocation          (1000163, 5)

In [16]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [17]:
category_translation = pd.read_sql(
    "SELECT * FROM product_category_translation",
    engine
)

category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [18]:
order_reviews = pd.read_sql(
    "SELECT * FROM order_reviews",
    engine
)

order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,,,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,,,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,,,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [19]:
table_data = {
    "orders": orders,
    "customers": customers,
    "products": products,
    "sellers": sellers,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "category_translation": category_translation,
    "geolocation": geolocation
}

row_counts = pd.DataFrame({
    "table": table_data.keys(),
    "rows": [df.shape[0] for df in table_data.values()],
    "columns": [df.shape[1] for df in table_data.values()]
})


row_counts

                  table     rows  columns
0                orders    99441        8
1             customers    99441        5
2              products    32951        9
3               sellers     3095        4
4           order_items   112650        7
5        order_payments   103886        5
6         order_reviews    70000        7
7  category_translation       71        2
8           geolocation  1000163        5

In [20]:
orders["order_id"].duplicated().sum()

0

In [21]:
customers["customer_id"].duplicated().sum()

0

In [22]:
products["product_id"].duplicated().sum()

0

In [23]:
sellers["seller_id"].duplicated().sum()

0

In [24]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

0

In [25]:
order_payments.duplicated(
    subset=["order_id", "payment_sequential"]
).sum()

0

In [26]:
items_per_order = (
    order_items
    .groupby("order_id")
    .size()
    .sort_values(ascending=False)
)

items_per_order.head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
2c2a19b5703863c908512d135aa6accc    12
c05d6a79e55da72ca780ce90364abed9    12
dtype: int64

In [27]:
payments_per_order = (
    order_payments
    .groupby("order_id")
    .size()
    .sort_values(ascending=False)
)

payments_per_order.head(10)

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
fedcd9f7ccdc8cba3a18defedd1a5547    19
ee9ca989fc93ba09a6eddc250ce01742    19
4bfcba9e084f46c8e3cb49b0fa6e6159    15
21577126c19bf11a0b91592e5844ba78    15
3c58bffb70dcf45f12bdf66a3c215905    14
4689b1816de42507a7d63a4617383c59    14
dtype: int64

In [28]:
items_agg = (
    order_items
    .groupby("order_id")
    .agg(
        total_items=("order_item_id", "count"),
        total_price=("price", "sum"),
        total_freight_value=("freight_value", "sum"),
        avg_item_price=("price", "mean")
    )
    .reset_index()
)

In [29]:
items_agg.head()

,order_id,total_items,total_price,total_freight_value,avg_item_price
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,58.90
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,239.90
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,199.00
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79,12.99
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,199.90

In [30]:
payments_agg = (
    order_payments
    .groupby("order_id")
    .agg(
        total_payment_value=("payment_value", "sum"),
        max_installments=("payment_installments", "max"),
        payment_count=("payment_sequential", "count")
    )
    .reset_index()
)

In [31]:
payments_agg.head()

,order_id,total_payment_value,max_installments,payment_count
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,2,1
1,00018f77f2f0320c557190d7a144bdd3,259.83,3,1
2,000229ec398224ef6ca0657da4fc703e,216.87,5,1
3,00024acbcdf0a6daa1e931b038114c75,25.78,2,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,3,1

In [32]:
payment_type = (
    order_payments
    .groupby("order_id")["payment_type"]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan)
    .reset_index()
    .rename(columns={"payment_type": "main_payment_type"})
)
payment_type.head()

                           order_id main_payment_type
0  00010242fe8c5a6d1ba2dd792cb16214       credit_card
1  00018f77f2f0320c557190d7a144bdd3       credit_card
2  000229ec398224ef6ca0657da4fc703e       credit_card
3  00024acbcdf0a6daa1e931b038114c75       credit_card
4  00042b26cf59d7ce69dfabb4e55b4fd9       credit_card

In [33]:
payments_agg = payments_agg.merge(
    payment_type,
    on="order_id",
    how="left"
)

In [34]:
reviews_agg = (
    order_reviews
    .groupby("order_id")
    .agg(
        review_score=("review_score", "mean"),
        review_count=("review_id", "count")
    )
    .reset_index()
)
reviews_agg.head()

                           order_id  review_score  review_count
0  00010242fe8c5a6d1ba2dd792cb16214           5.0             1
1  00018f77f2f0320c557190d7a144bdd3           4.0             1
2  000229ec398224ef6ca0657da4fc703e           5.0             1
3  00024acbcdf0a6daa1e931b038114c75           4.0             1
4  00042b26cf59d7ce69dfabb4e55b4fd9           5.0             1

In [35]:
ml_table = orders.copy()
print(ml_table.shape)
print(ml_table.head())

(99441, 8)
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp   order_approved_at  \
0    delivered      2017-10-02 10:56:33 2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37 2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49 2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06 2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39 2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0                    2017-10-18
1                    2018-08-13
2                    2018-09-04
3                    2017-12-15
4                    2018-02-26

In [36]:
ml_table = ml_table.merge(
    customers,
    on="customer_id",
    how="left"
)

In [37]:
ml_table.shape

(99441, 12)

In [38]:
ml_table = ml_table.merge(
    items_agg,
    on="order_id",
    how="left"
)

In [39]:
ml_table = ml_table.merge(
    payments_agg,
    on="order_id",
    how="left"
)

In [40]:
unique_products_per_order = (
    order_items
    .groupby("order_id")["product_id"]
    .nunique()
    .reset_index()
    .rename(columns={
        "product_id": "unique_products"
    })
)

In [41]:
ml_table = ml_table.merge(
    unique_products_per_order,
    on="order_id",
    how="left"
)

In [42]:
unique_sellers_per_order = (
    order_items
    .groupby("order_id")["seller_id"]
    .nunique()
    .reset_index()
    .rename(columns={
        "seller_id": "unique_sellers"
    })
)

In [43]:
ml_table = ml_table.merge(
    unique_sellers_per_order,
    on="order_id",
    how="left"
)

In [46]:
print("Rows:", len(ml_table))
print("Unique orders:", ml_table["order_id"].nunique())

Rows: 99441
Unique orders: 99441

In [47]:
ml_table["order_id"].duplicated().sum()

0

In [48]:
ml_table.isna().sum().sort_values(ascending=False)

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
unique_sellers                    775
total_price                       775
unique_products                   775
avg_item_price                    775
total_freight_value               775
total_items                       775
order_approved_at                 160
main_payment_type                   1
payment_count                       1
max_installments                    1
total_payment_value                 1
order_id                            0
customer_id                         0
customer_city                       0
customer_zip_code_prefix            0
customer_unique_id                  0
order_estimated_delivery_date       0
order_purchase_timestamp            0
order_status                        0
customer_state                      0
dtype: int64

In [49]:
ml_table["order_purchase_timestamp"] = pd.to_datetime(
    ml_table["order_purchase_timestamp"],
    errors="coerce"
)

In [50]:
ml_table["purchase_year"] = (
    ml_table["order_purchase_timestamp"].dt.year
)

ml_table["purchase_month"] = (
    ml_table["order_purchase_timestamp"].dt.month
)

ml_table["purchase_day"] = (
    ml_table["order_purchase_timestamp"].dt.day
)

ml_table["purchase_weekday"] = (
    ml_table["order_purchase_timestamp"].dt.weekday
)

ml_table["purchase_hour"] = (
    ml_table["order_purchase_timestamp"].dt.hour
)

In [51]:
ml_table["is_weekend"] = (
    ml_table["purchase_weekday"] >= 5
).astype(int)

In [52]:
ml_table["multi_seller"] = (
    ml_table["unique_sellers"] > 1
).astype(int)

In [53]:
ml_table["freight_ratio"] = (
    ml_table["total_freight_value"] /
    ml_table["total_price"].replace(0, np.nan)
)

In [54]:
ml_table["freight_per_item"] = (
    ml_table["total_freight_value"] /
    ml_table["total_items"].replace(0, np.nan)
)

In [55]:
print(products.columns.tolist())

['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

In [56]:
products["product_volume_cm3"] = (
    products["product_length_cm"]
    * products["product_height_cm"]
    * products["product_width_cm"]
)

In [57]:
order_product_data = order_items[
    [
        "order_id",
        "product_id"
    ]
].merge(
    products[
        [
            "product_id",
            "product_weight_g",
            "product_volume_cm3"
        ]
    ],
    on="product_id",
    how="left"
)

In [58]:
product_features = (
    order_product_data
    .groupby("order_id")
    .agg(
        total_weight=("product_weight_g", "sum"),
        total_volume=("product_volume_cm3", "sum"),
        avg_volume=("product_volume_cm3", "mean"),
        max_volume=("product_volume_cm3", "max")
    )
    .reset_index()
)

In [59]:
ml_table = ml_table.merge(
    product_features,
    on="order_id",
    how="left"
)

In [60]:
seller_order_data = (
    order_items[
        [
            "order_id",
            "seller_id"
        ]
    ]
    .merge(
        sellers[
            [
                "seller_id",
                "seller_zip_code_prefix",
                "seller_state"
            ]
        ],
        on="seller_id",
        how="left"
    )
)

In [61]:
geo_by_zip = (
    geolocation
    .groupby("geolocation_zip_code_prefix")
    .agg(
        latitude=("geolocation_lat", "mean"),
        longitude=("geolocation_lng", "mean")
    )
    .reset_index()
)

In [66]:
customer_geo = ml_table[
    [
        "order_id",
        "customer_zip_code_prefix"
    ]
].merge(
    geo_by_zip,
    left_on="customer_zip_code_prefix",
    right_on="geolocation_zip_code_prefix",
    how="left"
)

In [67]:
customer_geo = customer_geo.rename(
    columns={
        "latitude": "customer_lat",
        "longitude": "customer_lng"
    }
)

In [68]:
seller_geo = seller_order_data.merge(
    geo_by_zip,
    left_on="seller_zip_code_prefix",
    right_on="geolocation_zip_code_prefix",
    how="left"
)

In [69]:
seller_geo = seller_geo.rename(
    columns={
        "latitude": "seller_lat",
        "longitude": "seller_lng"
    }
)

In [70]:
def haversine_distance(
    lat1,
    lon1,
    lat2,
    lon2
):
    R = 6371

    lat1 = np.radians(lat1)
    lon1 = np.radians(lon1)

    lat2 = np.radians(lat2)
    lon2 = np.radians(lon2)

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        np.sin(dlat / 2) ** 2
        +
        np.cos(lat1)
        * np.cos(lat2)
        * np.sin(dlon / 2) ** 2
    )

    c = 2 * np.arcsin(
        np.sqrt(a)
    )

    return R * c

In [71]:
geo_orders = customer_geo.merge(
    seller_geo[
        [
            "order_id",
            "seller_id",
            "seller_state",
            "seller_lat",
            "seller_lng"
        ]
    ],
    on="order_id",
    how="left"
)

In [72]:
geo_orders["distance_km"] = haversine_distance(
    geo_orders["customer_lat"],
    geo_orders["customer_lng"],
    geo_orders["seller_lat"],
    geo_orders["seller_lng"]
)

In [73]:
geo_orders = geo_orders.merge(
    ml_table[
        [
            "order_id",
            "customer_state"
        ]
    ],
    on="order_id",
    how="left"
)

In [74]:
geo_orders["is_cross_state"] = (
    geo_orders["customer_state"]
    != geo_orders["seller_state"]
).astype(int)

In [75]:
geo_features = (
    geo_orders
    .groupby("order_id")
    .agg(
        distance_km=("distance_km", "mean"),
        is_cross_state=("is_cross_state", "max")
    )
    .reset_index()
)

In [76]:
ml_table = ml_table.merge(
    geo_features,
    on="order_id",
    how="left"
)

In [77]:
ml_table.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,is_weekend,multi_seller,freight_ratio,freight_per_item,total_weight,total_volume,avg_volume,max_volume,distance_km,is_cross_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,0,0,0.290764,8.72,500.0,1976.0,1976.0,1976.0,18.576110,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,0,0,0.191744,22.76,400.0,4693.0,4693.0,4693.0,851.495069,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,0,0,0.120200,19.22,420.0,9576.0,9576.0,9576.0,514.410666,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,1,0,0.604444,27.20,450.0,6000.0,6000.0,6000.0,1822.226336,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,0,0,0.438191,8.72,250.0,11475.0,11475.0,11475.0,29.676625,0

In [78]:
ml_table.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'total_items',
 'total_price',
 'total_freight_value',
 'avg_item_price',
 'total_payment_value',
 'max_installments',
 'payment_count',
 'main_payment_type',
 'unique_products',
 'unique_sellers',
 'purchase_year',
 'purchase_month',
 'purchase_day',
 'purchase_weekday',
 'purchase_hour',
 'is_weekend',
 'multi_seller',
 'freight_ratio',
 'freight_per_item',
 'total_weight',
 'total_volume',
 'avg_volume',
 'max_volume',
 'distance_km',
 'is_cross_state']

In [79]:
print(
    "Rows:",
    len(ml_table)
)

print(
    "Unique orders:",
    ml_table["order_id"].nunique()
)

Rows: 99441
Unique orders: 99441

In [80]:
print(
    "Duplicate order_ids:",
    ml_table["order_id"].duplicated().sum()
)

Duplicate order_ids: 0

In [81]:
new_features = [
    "purchase_year",
    "purchase_month",
    "purchase_day",
    "purchase_weekday",
    "purchase_hour",
    "is_weekend",
    "multi_seller",
    "freight_ratio",
    "freight_per_item",
    "total_weight",
    "total_volume",
    "avg_volume",
    "max_volume",
    "distance_km",
    "is_cross_state"
]

ml_table[new_features].describe().T

,count,mean,std,min,25%,50%,75%,max
purchase_year,99441.0,2017.539838,0.505007,2016.0,2017.000000,2018.000000,2018.000000,2.018000e+03
purchase_month,99441.0,6.032220,3.232999,1.0,3.000000,6.000000,8.000000,1.200000e+01
purchase_day,99441.0,15.505948,8.667298,1.0,8.000000,15.000000,23.000000,3.100000e+01
purchase_weekday,99441.0,2.755735,1.966495,0.0,1.000000,3.000000,4.000000,6.000000e+00
purchase_hour,99441.0,14.770879,5.326666,0.0,11.000000,15.000000,19.000000,2.300000e+01
is_weekend,99441.0,0.229754,0.420677,0.0,0.000000,0.000000,0.000000,1.000000e+00
multi_seller,99441.0,0.012852,0.112636,0.0,0.000000,0.000000,0.000000,1.000000e+00
freight_ratio,98666.0,0.308389,0.314762,0.0,0.131864,0.224374,0.380191,2.144706e+01
freight_per_item,98666.0,20.190469,15.797846,0.0,13.370000,16.360000,21.180000,4.096800e+02
total_weight,98666.0,2390.027669,4773.239825,0.0,300.000000,750.000000,2066.750000,1.844000e+05
total_volume,98666.0,17401.430037,30402.167635,0.0,2964.000000,7260.000000,19872.000000,1.476000e+06
avg_volume,98650.0,15221.598216,23368.209897,168.0,2816.000000,6426.000000,18375.000000,2.962080e+05
max_volume,98650.0,15366.969204,23576.251900,168.0,2850.000000,6480.000000,18711.000000,2.962080e+05
distance_km,98177.0,601.685266,594.946172,0.0,187.194611,433.792048,798.408741,8.677912e+03
is_cross_state,99441.0,0.644483,0.478672,0.0,0.000000,1.000000,1.000000,1.000000e+00

In [82]:
missing = (
    ml_table[new_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print(missing)

distance_km         1264
avg_volume           791
max_volume           791
freight_ratio        775
freight_per_item     775
total_weight         775
total_volume         775
purchase_year          0
purchase_month         0
purchase_day           0
purchase_weekday       0
purchase_hour          0
is_weekend             0
multi_seller           0
is_cross_state         0
dtype: int64

In [83]:
orders[
    [
        "order_id",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
].head(10)

,order_id,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-16 18:17:02,2018-02-26
5,a4591c265e18cb1dcee52889e2d8acc3,2017-07-26 10:57:55,2017-08-01
6,136cce7faa42fdb2cefd53fdc79a6098,NaT,2017-05-09
7,6514b8ad8028c9f2cc2374ded245783f,2017-05-26 12:55:51,2017-06-07
8,76c6e866289321a7c93b82b54852dc33,2017-02-02 14:08:10,2017-03-06
9,e69bfb5eb88e0ed6a785585b27e16dbf,2017-08-16 17:14:30,2017-08-23

In [84]:
ml_table[
    [
        "total_items",
        "total_price",
        "total_freight_value",
        "unique_products",
        "unique_sellers"
    ]
].isna().all(axis=1).sum()

775

In [85]:
ml_table[
    ml_table["total_items"].isna()
][
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp"
    ]
].head(20)

                              order_id order_status order_purchase_timestamp
266   8e24261a7e58791d10cb1bf9da94df5c  unavailable      2017-11-16 15:09:28
586   c272bcd21c287498b4883c7512019702  unavailable      2018-01-31 11:31:37
687   37553832a3a89c9b2db59701c357ca67  unavailable      2017-08-14 17:38:02
737   d57e15fb07fd180f06ab3926b39edcd2  unavailable      2018-01-08 19:39:03
1130  00b1cb0320190ca0daa2c88b35206009     canceled      2018-08-28 15:26:39
1160  2f634e2cebf8c0283e7ef0989f77d217  unavailable      2017-09-27 20:55:33
1579  ee0db22a8e742b752914016708470ec8  unavailable      2017-08-24 11:04:41
1801  ed3efbd3a87bea76c2812c66a0b32219     canceled      2018-09-20 13:54:16
1826  6ad57aecbae806a7e9cc2cdb6b380711  unavailable      2017-11-30 07:48:24
1868  df8282afe61008dc26c6c31011474d02     canceled      2017-03-04 12:14:30
2029  8d4c637f1accf7a88a4555f02741e606     canceled      2018-08-29 16:27:49
2148  9f3458f0433d4cfa472f4682654b8d49  unavailable      2017-07-18 23:36:55
2161  7a9d4c7f9b068337875b95465330f2fc     canceled      2017-05-01 16:12:39
2296  f0df036e9be21fc238f131bbfcdde769  unavailable      2017-02-24 23:39:21
2316  86f0bcd9b426a2c1022ae317c7f27be6  unavailable      2017-03-08 15:13:03
2680  98fe01bc254b759c1f2c11d77c2891d5  unavailable      2017-10-17 18:34:56
2707  f56dc9034c3962e36d49fb73baa12800  unavailable      2017-08-10 22:20:51
2971  0130f0f71fb0e831d18e6a3b33a3a50c  unavailable      2017-05-12 10:17:23
3056  ddaec6fff982b13e7e048b627a11d6da     canceled      2016-10-04 19:41:32
3084  84b8ba39037606b7b30a39d02e9e4154  unavailable      2018-06-27 19:51:02

In [86]:
missing_items_orders = set(
    ml_table.loc[
        ml_table["total_items"].isna(),
        "order_id"
    ]
)

existing_items_orders = set(order_items["order_id"])

len(missing_items_orders & existing_items_orders)

0

In [88]:
order_item_counts = (
    order_items
    .groupby("order_id")
    .size()
)

order_item_counts.describe()

count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
dtype: float64

In [89]:
order_item_counts.value_counts().sort_index().head(20)

1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

In [90]:
payment_counts = (
    order_payments
    .groupby("order_id")
    .size()
)

payment_counts.describe()

count    99440.000000
mean         1.044710
std          0.381166
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         29.000000
dtype: float64

In [91]:
payment_counts.value_counts().sort_index()

1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

In [92]:
print("Duplicate order_id:",
      orders["order_id"].duplicated().sum())

print("Duplicate customer_id:",
      customers["customer_id"].duplicated().sum())

print("Duplicate product_id:",
      products["product_id"].duplicated().sum())

print("Duplicate seller_id:",
      sellers["seller_id"].duplicated().sum())

print(
    "Duplicate order_id + order_item_id:",
    order_items.duplicated(
        subset=["order_id", "order_item_id"]
    ).sum()
)

print(
    "Duplicate order_id + payment_sequential:",
    order_payments.duplicated(
        subset=["order_id", "payment_sequential"]
    ).sum()
)

Duplicate order_id: 0
Duplicate customer_id: 0
Duplicate product_id: 0
Duplicate seller_id: 0
Duplicate order_id + order_item_id: 0
Duplicate order_id + payment_sequential: 0

In [93]:
ml_table[
    ml_table["order_delivered_customer_date"].isna()
]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [94]:
ml_table[
    ml_table["order_delivered_customer_date"].notna()
]["order_status"].value_counts()

order_status
delivered    96470
canceled         6
Name: count, dtype: int64

In [96]:
ml_table.to_csv(
    "olist_ml_table_new_new_new.csv",
    index=False
)

In [97]:
final_check = pd.read_csv(
    "olist_ml_table_new_new_new.csv"
)

print("Shape:", final_check.shape)

print(
    "Unique orders:",
    final_check["order_id"].nunique()
)

print(
    "Duplicate order IDs:",
    final_check["order_id"].duplicated().sum()
)

Shape: (99441, 37)
Unique orders: 99441
Duplicate order IDs: 0